global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'kamon-akka'
      static_configs:
          - targets: ['localhost:9090', 'localhost:9095']