version: '3.3'

volumes:
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090'
  akka_kamon:
    image: akka_kamon:latest
    ports:
        - '8080:8080'
        - '9095:9095'

  grafana:
      image: grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
      env_file:
        - ./grafana/config.monitoring
      restart: always
