version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090'
  akka_kamon:
    image: akka_kamon:latest
    ports:
        - '8080'
        - '9095:9095'