FROM openjdk:10
LABEL maintainer="gucluakkaya@gmail.com"
LABEL description="container for akka-kamon-maven sample"

COPY akka-kamon-maven-0.0.2-SNAPSHOT.jar /home/akka-kamon-maven.jar
CMD ["java","-jar","/home/akka-kamon-maven.jar"]